---
# Disable JSHint as it's deprecated and doesn't support ES2022+ features
# The project uses ESLint for linting which fully supports modern JavaScript
engines:
  jshint:
    enabled: false
  markdownlint:
    enabled: false
  duplication:
    exclude_paths:
      - "test/**"
      - "docs/**"

exclude_paths:
  - "node_modules/**"
  - "dist/**"
  - "coverage/**"
  - "docs/**"
  - "**/*.min.js"
  - ".github/**"
  - "**/*.md"
