---
# Codacy Configuration
# Disable deprecated/unsupported tools
engines:
  jshint:
    enabled: false
  markdownlint:
    enabled: false
  csslint:
    enabled: false
  duplication:
    enabled: false
  metrics:
    enabled: false

# Exclude paths from all analysis
exclude_paths:
  - "node_modules/**"
  - "dist/**"
  - "coverage/**"
  - "docs/**"
  - "test/**"
  - "benchmarks/**"
  - "scripts/**"
  - ".github/**"
  - "packages/core/test/**"
  - "**/*.md"
  - "**/*.d.ts"
  - "**/*.min.js"
